### ISSUE TITLE
Docker Container?

### ISSUE THREAD

**Issue by 0x27** [stasinopoulos/commix-testbed#2]
It might be interesting to make the testbed available as a Docker container.

I got it working in Docker with the following image: https://hub.docker.com/r/linode/lamp/

I just removed the index.html in /var/www/example.com/public_html/, did "apt install git", and git cloned the testbed into that directory. Worked out of the box just fine :)

Annoyingly Linode didn't provide a Dockerfile for their image, so one might have to redo all their work or something in order to ship an image.

**Comment by JustAGuyWhoDoesThings** [comment]
Well you could just make and distribute your own docker container with this project loaded in as i would also like a way to quickly download this and get it running in a temp env. And it would be cool for people like me who just wanna get it running until it gets its own official docker container

**Comment by stasinopoulos** [comment]
Here you are https://hub.docker.com/r/commixproject/commix-testbed :)
