### ISSUE TITLE
page garbled Chinese environment

### ISSUE THREAD

**Issue by wolf-li** [stasinopoulos/commix-testbed#3]
My computer is windows 10 chinese version.When I run this,page garbled.
I suggest the writer using "<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />".
Problem solve.

**Comment by stasinopoulos** [comment]
Could you provide me with detailed info about the problem?

**Comment by wolf-li** [comment]
Yes,I wrote a docment.Check it.
My english is not good.Maybe my point was not clear.
If i was wrong.Tell me.


Hermann LI

**Comment by wolf-li** [comment]
Yes,I wrote a docment.Check it.
My english is not good.Maybe my point was not clear.
If i was wrong.Tell me.


Hermann LI

**Comment by stasinopoulos** [comment]
What document?

**Comment by wolf-li** [comment]
I have been send you two messages. The last one.If you did not find. This message has.

**Comment by stasinopoulos** [comment]
Sorry i don't understand.
